
name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: volkan erturk test
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          browser: firefox
          record: true
          parallel: true
        env:
          # for recording test results and videos to Cypress Dashboard
          CYPRESS_RECORD_KEY: fe290e49-d8ee-42f4-8058-436d673b5b63

          
